spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bcptestdb
    username: sa
    password: h2-password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always